# Creating the `LIB` table

From the `books_df` that was created in a different notebook I will contruct a `LIB` table.

## Import Packages

In [106]:
import pandas as pd
import re

## Set the Data Path

In [107]:
file_location = 'C:/Users/mason/Box/Text As Data Final/Output'
books_df = pd.read_csv(file_location + '/BrandonSandersonBooks.csv')
books_df.head()

,title,file_path,author,date,chapter_id,paragraph_id,text
0,A Memory of Light,C:/Users/mason/Box/Text As Data Final/Sanderso...,Robert Jordan & Brandon Sanderson,2013-01-08,0,0,by Robert Jordan
1,A Memory of Light,C:/Users/mason/Box/Text As Data Final/Sanderso...,Robert Jordan & Brandon Sanderson,2013-01-08,0,1,The Eye of the World
2,A Memory of Light,C:/Users/mason/Box/Text As Data Final/Sanderso...,Robert Jordan & Brandon Sanderson,2013-01-08,0,2,The Great Hunt
3,A Memory of Light,C:/Users/mason/Box/Text As Data Final/Sanderso...,Robert Jordan & Brandon Sanderson,2013-01-08,0,3,The Dragon Reborn
4,A Memory of Light,C:/Users/mason/Box/Text As Data Final/Sanderso...,Robert Jordan & Brandon Sanderson,2013-01-08,0,4,The Shadow Rising

## Correct the chapter_id

I don't want all of the beginning cruft but I do want the prologue for each book as chapter 0

In [108]:
start_pattern = r'^[\W_]*(?:Prologue|Preface|Introduction|Foreword|Chapter 1|Chapter One|Book One|Book 1|Part One|Part 1|The Wheel of Time turns|GOD.S DEATH|YOU WANT|Eshonai|Yeah. he.dheard|Nomad woke up|In the middle|Right about then|Elantris was beautiful|Starling hopped|ASH FELL FROM THE SKY|Lord Tresting frowned)\b'
end_pattern = r'^\s*(?:Endnotes|About the Author|Glossary|Ars Arcanum|Postscript|POSTSCRIPT|Epilogue|EPILOGUE|Afterword|Also by Brandon Sanderson|Illustrations:|THE END)\b'

books_df['temp_word_count'] = books_df['text'].str.split().str.len()
books_df['is_short_line'] = books_df['temp_word_count'] < 10
books_df['short_density'] = books_df.groupby('file_path')['is_short_line'].transform(
    lambda x: x.rolling(window=15, center=True, min_periods=1).sum()
)
is_not_toc = books_df['short_density'] < 12

raw_is_start = books_df['text'].str.contains(start_pattern, flags=re.IGNORECASE, regex=True, na=False)

books_df['is_start'] = raw_is_start & is_not_toc
books_df['has_started'] = books_df.groupby('file_path')['is_start'].cumsum()

book_has_any_start = books_df.groupby('file_path')['is_start'].transform('max')

valid_start_mask = (books_df['has_started'] > 0) | (book_has_any_start == 0) & (books_df['chapter_id']> 0)

raw_is_end = books_df['text'].str.contains(end_pattern, flags=re.IGNORECASE, regex=True, na=False)
books_df['is_end'] = raw_is_end & valid_start_mask & is_not_toc
books_df['has_ended'] = books_df.groupby('file_path')['is_end'].cumsum()

valid_end_mask = (books_df['has_ended'] == 0)

clean_books_df = books_df[valid_start_mask & valid_end_mask].copy()

clean_books_df = clean_books_df.drop(columns=['is_start', 'is_end', 'has_started', 'has_ended', 'is_short_line', 'short_density', 'temp_word_count'])
clean_books_df = clean_books_df.reset_index(drop=True)

print(f"Original number of rows: {len(books_df)}")
print(f"Cleaned number of rows: {len(clean_books_df)}")

LIB_titles = clean_books_df['title'].unique()
print(f"Unique book titles in the cleaned dataset ({len(LIB_titles)}):")
print(LIB_titles)

Original number of rows: 287646
Cleaned number of rows: 86466
Unique book titles in the cleaned dataset (24):
<StringArray>
[             'A Memory of Light',              'Arcanum Unbounded',
                       'Elantris',         'Isles of the Emberdark',
                    'Oathbringer',                  'Rhythm of War',
                'Shadows of Self',                     'Steelheart',
            'The Aether of Night',               'The Alloy of Law',
          'The Bands of Mourning',               'The Final Empire',
               'The Hero of Ages',                 'The Lost Metal',
                 'The Sunlit Man',               'The Way of Kings',
          'The Well of Ascension',              'The Wheel of Time',
             'Towers of Midnight',       'Tress of the Emerald Sea',
                     'Warbreaker',                 'Wind and Truth',
              'Words of Radiance', 'Yumi and the Nightmare Painter']
Length: 24, dtype: str

## Still getting wierd Chapter Patterns lets clean that up

In [109]:
number_words = r"One|Two|Three|Four|Five|Six|Seven|Eight|Nine|Ten|Eleven|Twelve|Thirteen|Fourteen|Fifteen|Sixteen|Seventeen|Eighteen|Nineteen|Twenty|Thirty|Forty|Fifty|Sixty|Seventy|Eighty|Ninety|Hundred"

chapter_pattern = rf'^\s*(?:Prologue|Epilogue|Preface|Introduction|Foreword|Chapter|Interlude|Part|Book)\b|^\s*\d{{1,3}}[.:-]?\s*$|^\s*(?:{number_words}|-)+\s*$'

clean_books_df['is_new_chapter'] = clean_books_df['text'].str.contains(
    chapter_pattern, flags=re.IGNORECASE, regex=True, na=False)

clean_books_df['logical_chapter_id'] = clean_books_df.groupby('file_path')['is_new_chapter'].cumsum()

## Diagnostic View of each Title

In [110]:
diagnostic_df = clean_books_df.copy()
diagnostic_df['text_preview'] = diagnostic_df['text'].astype(str).str[:100].str.replace('\n', ' ')+'...'


first_few = diagnostic_df.groupby('title').head(5)
last_few = diagnostic_df.groupby('title').tail(5)


boundaries_df = pd.concat([first_few, last_few]).drop_duplicates().sort_values(['title', 'logical_chapter_id'])

## Get Book Length, number of chapters, Number of Paragraphs

In [111]:
clean_books_df['word_count'] = clean_books_df['text'].str.split().str.len()

clean_books_df['is_real_paragraph'] = clean_books_df['word_count'] > 3

valid_text_df = clean_books_df[clean_books_df['is_real_paragraph']]
chapter_counts = valid_text_df.groupby('file_path')['logical_chapter_id'].nunique().reset_index(name='Total_chapters')

lib_df = clean_books_df.groupby(
    ['title', 'file_path', 'author', 'date'],
    dropna=False
).agg(
    length_in_words=('word_count', 'sum'),
    Total_paragraphs=('is_real_paragraph', 'sum')
).reset_index()

lib_df = lib_df.merge(chapter_counts, on='file_path', how='left')

lib_df = lib_df.rename(columns={
    'file_path': 'File_path',
    'author': 'Author',
    'date': 'Date',
    'length_in_words': 'Length',
})

lib_df = lib_df[['title', 'Author', 'Date', 'Length', 'Total_chapters', 'Total_paragraphs', 'File_path']]
lib_df = lib_df.sort_values('title').reset_index(drop=True)

clean_books_df = clean_books_df.drop(columns=['word_count', 'is_real_paragraph', 'is_new_chapter'])

with pd.option_context('display.max_rows', None, 'display.max_columns', 1000):
    print(lib_df)

                             title                             Author  \
0                A Memory of Light  Robert Jordan & Brandon Sanderson
1                Arcanum Unbounded                  Brandon Sanderson
2                         Elantris                  Brandon Sanderson
3           Isles of the Emberdark                  Brandon Sanderson
4                      Oathbringer                  Brandon Sanderson
5                    Rhythm of War                  Brandon Sanderson
6                  Shadows of Self                  Brandon Sanderson
7                       Steelheart                  Brandon Sanderson
8              The Aether of Night                 Sanderson, Brandon
9                 The Alloy of Law                  Brandon Sanderson
10           The Bands of Mourning                 Sanderson, Brandon
11                The Final Empire                  Brandon Sanderson
12                The Hero of Ages                  Brandon Sanderson
13                  The Lost Metal                 Sanderson, Brandon
14                  The Sunlit Man                  Brandon Sanderson
15                The Way of Kings                  Brandon Sanderson
16           The Well of Ascension                  Brandon Sanderson
17               The Wheel of Time                      Robert Jordan
18              Towers of Midnight                     Unknown Author
19        Tress of the Emerald Sea                  Brandon Sanderson
20                      Warbreaker                  Brandon Sanderson
21                  Wind and Truth                  Brandon Sanderson
22               Words of Radiance                 Sanderson, Brandon
23  Yumi and the Nightmare Painter                  Brandon Sanderson

                                Date  Length  Total_chapters  \
0                         2013-01-08  279300               1
1                       Unknown Date   30328               2
2          2004-12-31T15:00:00+00:00  199771               1
3                               2025   35349               1
4                       Unknown Date  117420               1
5   2020-11-16T21:59:24.296112+00:00   72734               2
6                         2015-11-06   44530               1
7                       Unknown Date   95094              47
8          0101-01-01T00:00:00+00:00  131769               1
9          2012-10-29T18:00:00+00:00   41205               1
10         2016-01-26T06:00:00+00:00  123542              26
11         2008-01-15T05:00:00+00:00   55717               7
12                      Unknown Date   16354               1
13                      Unknown Date  155764               2
14                        2023-10-01   63512               1
15         2010-01-01T00:00:00+00:00   59609               8
16                        2007-08-21   18914               1
17         2014-07-29T04:00:00+00:00  277597               3
18                      Unknown Date   74735              14
19                           2023-01  105914               1
20                        2009-06-09   99231               1
21         2024-12-05T18:30:00+00:00   37466               1
22         2014-03-03T22:00:00+00:00   26590               1
23                        2023-07-01    1075               1

    Total_paragraphs                                          File_path
0               8694  C:/Users/mason/Box/Text As Data Final/Sanderso...
1                946  C:/Users/mason/Box/Text As Data Final/Sanderso...
2               6372  C:/Users/mason/Box/Text As Data Final/Sanderso...
3               1212  C:/Users/mason/Box/Text As Data Final/Sanderso...
4               4002  C:/Users/mason/Box/Text As Data Final/Sanderso...
5               2213  C:/Users/mason/Box/Text As Data Final/Sanderso...
6               1454  C:/Users/mason/Box/Text As Data Final/Sanderso...
7              15227  C:/Users/mason/Box/Text As Data Final/Sanderso...
8               4532  C:/Users/mason/Box/Text As Data Final/Sanderso...
9               1336  C:/Users/mason/Box/Text As Data Final/Sanderso...
10              4471  C:/Users/mason/Box/Text As Data Final/Sanderso...
11              1862  C:/Users/mason/Box/Text As Data Final/Sanderso...
12               499  C:/Users/mason/Box/Text As Data Final/Sanderso...
13              5420  C:/Users/mason/Box/Text As Data Final/Sanderso...
14              2005  C:/Users/mason/Box/Text As Data Final/Sanderso...
15              1684  C:/Users/mason/Box/Text As Data Final/Sanderso...
16               628  C:/Users/mason/Box/Text As Data Final/Sanderso...
17              5729  C:/Users/mason/Box/Text As Data Final/Sanderso...
18              2304  C:/Users/mason/Box/Text As Data Final/Sanderso...
19              3450  C:/Users/mason/Box/Text As Data Final/Sanderso...
20              3524  C:/Users/mason/Box/Text As Data Final/Sanderso...
21              1295  C:/Users/mason/Box/Text As Data Final/Sanderso...
22               948  C:/Users/mason/Box/Text As Data Final/Sanderso...
23                45  C:/Users/mason/Box/Text As Data Final/Sanderso...

## Fix the Dates Column

In [112]:
lib_df['Date'] = pd.to_datetime(lib_df['Date'], errors='coerce', utc=True)
lib_df.loc[lib_df['Date'].dt.year < 1900, 'Date'] = pd.NaT
lib_df['Date'] = lib_df['Date'].dt.tz_localize(None)
#lib_df['Date'] = lib_df['Date'].dt.strftime('%Y-%m-%d')
print(lib_df[['title', 'Date']])

                             title       Date
0                A Memory of Light 2013-01-08
1                Arcanum Unbounded        NaT
2                         Elantris        NaT
3           Isles of the Emberdark        NaT
4                      Oathbringer        NaT
5                    Rhythm of War        NaT
6                  Shadows of Self 2015-11-06
7                       Steelheart        NaT
8              The Aether of Night        NaT
9                 The Alloy of Law        NaT
10           The Bands of Mourning        NaT
11                The Final Empire        NaT
12                The Hero of Ages        NaT
13                  The Lost Metal        NaT
14                  The Sunlit Man 2023-10-01
15                The Way of Kings        NaT
16           The Well of Ascension 2007-08-21
17               The Wheel of Time        NaT
18              Towers of Midnight        NaT
19        Tress of the Emerald Sea        NaT
20                      Warbreaker 2009-06-09
21                  Wind and Truth        NaT
22               Words of Radiance        NaT
23  Yumi and the Nightmare Painter 2023-07-01

In [113]:
missing_dates = lib_df[lib_df['Date'].isna()]
print("Books with missing or invalid dates:")
print(missing_dates[['title', 'Date']])

Books with missing or invalid dates:
                       title Date
1          Arcanum Unbounded  NaT
2                   Elantris  NaT
3     Isles of the Emberdark  NaT
4                Oathbringer  NaT
5              Rhythm of War  NaT
7                 Steelheart  NaT
8        The Aether of Night  NaT
9           The Alloy of Law  NaT
10     The Bands of Mourning  NaT
11          The Final Empire  NaT
12          The Hero of Ages  NaT
13            The Lost Metal  NaT
15          The Way of Kings  NaT
17         The Wheel of Time  NaT
18        Towers of Midnight  NaT
19  Tress of the Emerald Sea  NaT
21            Wind and Truth  NaT
22         Words of Radiance  NaT

In [114]:
found_dates = {
    'Arcanum Unbounded': '2016-11-22',
    'Elantris': '2005-04-21',
    'Isles of the Emberdark': '2025-01-01',
    'Oathbringer': '2017-11-14',
    'Rhythm of War': '2020-11-17',
    'Steelheart': '2013-09-24',
    'The Aether of Night': '2003-01-01', 
    'The Alloy of Law': '2011-11-08',
    'The Bands of Mourning': '2016-01-26',
    'The Final Empire': '2006-07-17',
    'The Hero of Ages': '2008-10-14',
    'The Lost Metal': '2022-11-15',
    'The Way of Kings': '2010-08-31',
    'The Wheel of Time': '1990-01-15',
    'Towers of Midnight': '2010-11-02',
    'Tress of the Emerald Sea': '2023-01-01',
    'Wind and Truth': '2024-12-06',
    'Words of Radiance': '2014-03-04'
}

replacement_dates = lib_df['title'].map(found_dates)
replacement_dates = pd.to_datetime(replacement_dates)
lib_df['Date'] = lib_df['Date'].fillna(replacement_dates)
lib_df['Date'] = lib_df['Date'].dt.strftime('%Y-%m-%d')
print(lib_df[['title', 'Date']])

                             title        Date
0                A Memory of Light  2013-01-08
1                Arcanum Unbounded  2016-11-22
2                         Elantris  2005-04-21
3           Isles of the Emberdark  2025-01-01
4                      Oathbringer  2017-11-14
5                    Rhythm of War  2020-11-17
6                  Shadows of Self  2015-11-06
7                       Steelheart  2013-09-24
8              The Aether of Night  2003-01-01
9                 The Alloy of Law  2011-11-08
10           The Bands of Mourning  2016-01-26
11                The Final Empire  2006-07-17
12                The Hero of Ages  2008-10-14
13                  The Lost Metal  2022-11-15
14                  The Sunlit Man  2023-10-01
15                The Way of Kings  2010-08-31
16           The Well of Ascension  2007-08-21
17               The Wheel of Time  1990-01-15
18              Towers of Midnight  2010-11-02
19        Tress of the Emerald Sea  2023-01-01
20                      Warbreaker  2009-06-09
21                  Wind and Truth  2024-12-06
22               Words of Radiance  2014-03-04
23  Yumi and the Nightmare Painter  2023-07-01

In [115]:
print(lib_df)

                             title                             Author  \
0                A Memory of Light  Robert Jordan & Brandon Sanderson
1                Arcanum Unbounded                  Brandon Sanderson
2                         Elantris                  Brandon Sanderson
3           Isles of the Emberdark                  Brandon Sanderson
4                      Oathbringer                  Brandon Sanderson
5                    Rhythm of War                  Brandon Sanderson
6                  Shadows of Self                  Brandon Sanderson
7                       Steelheart                  Brandon Sanderson
8              The Aether of Night                 Sanderson, Brandon
9                 The Alloy of Law                  Brandon Sanderson
10           The Bands of Mourning                 Sanderson, Brandon
11                The Final Empire                  Brandon Sanderson
12                The Hero of Ages                  Brandon Sanderson
13                  The Lost Metal                 Sanderson, Brandon
14                  The Sunlit Man                  Brandon Sanderson
15                The Way of Kings                  Brandon Sanderson
16           The Well of Ascension                  Brandon Sanderson
17               The Wheel of Time                      Robert Jordan
18              Towers of Midnight                     Unknown Author
19        Tress of the Emerald Sea                  Brandon Sanderson
20                      Warbreaker                  Brandon Sanderson
21                  Wind and Truth                  Brandon Sanderson
22               Words of Radiance                 Sanderson, Brandon
23  Yumi and the Nightmare Painter                  Brandon Sanderson

          Date  Length  Total_chapters  Total_paragraphs  \
0   2013-01-08  279300               1              8694
1   2016-11-22   30328               2               946
2   2005-04-21  199771               1              6372
3   2025-01-01   35349               1              1212
4   2017-11-14  117420               1              4002
5   2020-11-17   72734               2              2213
6   2015-11-06   44530               1              1454
7   2013-09-24   95094              47             15227
8   2003-01-01  131769               1              4532
9   2011-11-08   41205               1              1336
10  2016-01-26  123542              26              4471
11  2006-07-17   55717               7              1862
12  2008-10-14   16354               1               499
13  2022-11-15  155764               2              5420
14  2023-10-01   63512               1              2005
15  2010-08-31   59609               8              1684
16  2007-08-21   18914               1               628
17  1990-01-15  277597               3              5729
18  2010-11-02   74735              14              2304
19  2023-01-01  105914               1              3450
20  2009-06-09   99231               1              3524
21  2024-12-06   37466               1              1295
22  2014-03-04   26590               1               948
23  2023-07-01    1075               1                45

                                            File_path
0   C:/Users/mason/Box/Text As Data Final/Sanderso...
1   C:/Users/mason/Box/Text As Data Final/Sanderso...
2   C:/Users/mason/Box/Text As Data Final/Sanderso...
3   C:/Users/mason/Box/Text As Data Final/Sanderso...
4   C:/Users/mason/Box/Text As Data Final/Sanderso...
5   C:/Users/mason/Box/Text As Data Final/Sanderso...
6   C:/Users/mason/Box/Text As Data Final/Sanderso...
7   C:/Users/mason/Box/Text As Data Final/Sanderso...
8   C:/Users/mason/Box/Text As Data Final/Sanderso...
9   C:/Users/mason/Box/Text As Data Final/Sanderso...
10  C:/Users/mason/Box/Text As Data Final/Sanderso...
11  C:/Users/mason/Box/Text As Data Final/Sanderso...
12  C:/Users/mason/Box/Text As Data Final/Sanderso...
13  C:/Users/mason/Box/Text As Data Final/Sanderso...
14  C:/Users/mason/Box/Text As Data Final/Sanderso...
15  C:/Users/mason/Box/Text As Data Final/Sanderso...
16  C:/Users/mason/Box/Text As Data Final/Sanderso...
17  C:/Users/mason/Box/Text As Data Final/Sanderso...
18  C:/Users/mason/Box/Text As Data Final/Sanderso...
19  C:/Users/mason/Box/Text As Data Final/Sanderso...
20  C:/Users/mason/Box/Text As Data Final/Sanderso...
21  C:/Users/mason/Box/Text As Data Final/Sanderso...
22  C:/Users/mason/Box/Text As Data Final/Sanderso...
23  C:/Users/mason/Box/Text As Data Final/Sanderso...

In [116]:
author_corrections ={
    'Sanderson, Brandon': 'Brandon Sanderson',
    'Unkown Author': 'Robert Jordan & Brandon Sanderson'
}
lib_df['Author'] = lib_df['Author'].replace(author_corrections)
print(lib_df[['title', 'Author']])

                             title                             Author
0                A Memory of Light  Robert Jordan & Brandon Sanderson
1                Arcanum Unbounded                  Brandon Sanderson
2                         Elantris                  Brandon Sanderson
3           Isles of the Emberdark                  Brandon Sanderson
4                      Oathbringer                  Brandon Sanderson
5                    Rhythm of War                  Brandon Sanderson
6                  Shadows of Self                  Brandon Sanderson
7                       Steelheart                  Brandon Sanderson
8              The Aether of Night                  Brandon Sanderson
9                 The Alloy of Law                  Brandon Sanderson
10           The Bands of Mourning                  Brandon Sanderson
11                The Final Empire                  Brandon Sanderson
12                The Hero of Ages                  Brandon Sanderson
13                  The Lost Metal                  Brandon Sanderson
14                  The Sunlit Man                  Brandon Sanderson
15                The Way of Kings                  Brandon Sanderson
16           The Well of Ascension                  Brandon Sanderson
17               The Wheel of Time                      Robert Jordan
18              Towers of Midnight                     Unknown Author
19        Tress of the Emerald Sea                  Brandon Sanderson
20                      Warbreaker                  Brandon Sanderson
21                  Wind and Truth                  Brandon Sanderson
22               Words of Radiance                  Brandon Sanderson
23  Yumi and the Nightmare Painter                  Brandon Sanderson

In [117]:
lib_df.head()

,title,Author,Date,Length,Total_chapters,Total_paragraphs,File_path
0,A Memory of Light,Robert Jordan & Brandon Sanderson,2013-01-08,279300,1,8694,C:/Users/mason/Box/Text As Data Final/Sanderso...
1,Arcanum Unbounded,Brandon Sanderson,2016-11-22,30328,2,946,C:/Users/mason/Box/Text As Data Final/Sanderso...
2,Elantris,Brandon Sanderson,2005-04-21,199771,1,6372,C:/Users/mason/Box/Text As Data Final/Sanderso...
3,Isles of the Emberdark,Brandon Sanderson,2025-01-01,35349,1,1212,C:/Users/mason/Box/Text As Data Final/Sanderso...
4,Oathbringer,Brandon Sanderson,2017-11-14,117420,1,4002,C:/Users/mason/Box/Text As Data Final/Sanderso...

## Upload and Save the `LIB` table
We did drop the Total_Chapters and Total_Paragrpahs Columns as they were inconsistent when pulling from the epub formatting

In [118]:
lib_df.to_csv(file_location + '/BrandonSanderson_LIB.csv', index=False)